## model hyperparameters
context_len: 1024  # called block_size in the video
n_embed: 768
vocab_size: 50257
n_layer: 12
n_head: 12

## Learning hyperparameters
batch_size: 64
max_iters: 5000
eval_interval: 500
eval_iters: 200
learning_rate: 3e-4
dropout: 0.2